Update Banner with Google Map Integration
BizTech-Morocco/mosa3ada.biztech.ma pull request #45
Opened 2023-09-15 17:41 UTC by hassankarrach

This pull request updates the banner by incorporating a Google Map element and introduces a new file, Data.js, to store location information for villages (for marker placement on the map).

Changes:

Added Google Map integration to the banner.
Introduced Data.js to hold village location data for map markers.

Please review and merge.

![image](https://github.com/BizTech-Morocco/mosa3ada.biztech.ma/assets/80120118/8f056e45-5d70-43ed-b567-1961554bace7)

2023-09-15 21:10 UTC, soufyanelf requested changes

2023-09-17 14:38 UTC, soufyanelf commented
@hassankarrach Are you working on the map integration? if not I'll jump into it sometime next week

2023-09-17 15:52 UTC, hassankarrach commented on src/components/Header/index.jsx
> +//MaterialUI
I'm a bit unsure about whether toggling between the map and the list is the perfect choice.

2023-09-17 16:43 UTC, soufyanelf commented on src/components/Header/index.jsx
> +//MaterialUI
If you want ui/ux feedback and maybe a mockup please highlight this discussion in the mosa3ada-ui-ux channel in discord https://discord.com/invite/pjyW6Zje

2023-09-23 02:11 UTC, soufyanelf commented
Im going to close this PR. we are not going to use Google Maps we will use Mapbox instead.

2023-09-23 02:12 UTC, closed without merging